# Generated by Django 4.1.2 on 2022-11-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QrModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qr_png", models.ImageField(upload_to=None)),
            ],
            options={
                "verbose_name": "Qr",
                "verbose_name_plural": "Qr-s",
            },
        ),
    ]
