# Generated by Django 4.1.2 on 2022-10-28 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Обрабатывается', 'Processing'), ('Успешно', 'Ok'), ('Неверно', 'Bad'), ('Ожидание превышено', 'Late'), ('Отклонено', 'Rejected')], default='Обрабатывается', max_length=18, verbose_name='Статус')),
                ('amount', models.IntegerField(verbose_name='Сумма перевода')),
                ('count_of_transactions', models.IntegerField(default=0, verbose_name='Количество транзакций')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver_transactions', to='bank_account.bankaccount')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='send_transactions', to='bank_account.bankaccount')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакций',
            },
        ),
    ]
