# Generated by Django 4.1.2 on 2022-11-01 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Обрабатывается', 'Processing'), ('Успешно', 'Ok'), ('Неверно', 'Bad'), ('Ожидание превышено', 'Late'), ('Отклонено', 'Rejected')], default='Обрабатывается', max_length=18, verbose_name='Статус')),
                ('amount', models.IntegerField(verbose_name='Сумма перевода')),
                ('sender_sign', models.CharField(max_length=255, verbose_name='Подпись отправителя.')),
                ('commission', models.IntegerField(verbose_name='Сумма комиссии')),
                ('verificated_code', models.CharField(max_length=5, null=True, verbose_name='Код подтверждения')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver_transactions', to='bank_account.bankaccount')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='send_transactions', to='bank_account.bankaccount')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакций',
            },
        ),
    ]
