# Generated by Django 4.1.2 on 2022-10-19 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Время удаления')),
                ('address', models.CharField(max_length=200, unique=True, verbose_name='Адрес счета')),
                ('balance', models.IntegerField(default=0, verbose_name='Остаток')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Владелец', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Обрабатывается', 'Processing'), ('Успешно', 'Ok'), ('Неверно', 'Bad'), ('Ожидание превышено', 'Late'), ('Отклонено', 'Rejected')], default='Обрабатывается', max_length=18, verbose_name='Статус')),
                ('amount', models.IntegerField(verbose_name='Сумма перевода')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiv_transactions', to='transactions.bankaccount')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='send_transactions', to='transactions.bankaccount')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакций',
            },
        ),
    ]
