# Generated by Django 4.1.2 on 2022-10-21 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="count_of_transactions",
            field=models.IntegerField(default=0, verbose_name="Количество транзакций"),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receiver_transactions",
                to="transactions.bankaccount",
            ),
        ),
    ]
