# Generated by Django 4.1.2 on 2022-10-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_alter_transactions_receiver"),
        ("transactions", "0002_transactions_count_of_transactions_and_more"),
    ]

    operations = []
