# Generated by Django 4.1.2 on 2022-10-21 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bank_account", "0001_initial"),
        ("transactions", "0003_merge_20221021_1807"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receiver_transactions",
                to="bank_account.bankaccount",
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="send_transactions",
                to="bank_account.bankaccount",
            ),
        ),
        migrations.DeleteModel(
            name="BankAccount",
        ),
    ]
