# Generated by Django 4.1.2 on 2022-10-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_remove_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
